package io.holbein.ephor.api.model.enums;

public enum AuditAction {
    VULNERABILITY_STATUS_CHANGED,
    VULNERABILITY_ASSIGNED,
    ESCALATION_CREATED,
    ESCALATION_STATUS_CHANGED,
    TRIAGE_DECISION_MADE,
    TRIAGE_SESSION_STARTED,
    TRIAGE_SESSION_COMPLETED,
    COMMENT_ADDED,
    COMMENT_UPDATED,
    COMMENT_DELETED,
    REMEDIATION_UPDATED
}
