package io.holbein.ephor.api.model.enums;

public enum Permission {
    VIEW_VULNERABILITIES,
    MANAGE_VULNERABILITIES,
    VIEW_ESCALATIONS,
    MANAGE_ESCALATIONS,
    VIEW_TRIAGE,
    MANAGE_TRIAGE,
    VIEW_REMEDIATIONS,
    MANAGE_REMEDIATIONS,
    VIEW_ADMIN,
    MANAGE_ADMIN
}
