{{- if include "ephor.database.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ephor.database.secretName" . }}
  labels:
    {{- include "ephor.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
    {{- if .Values.postgresql.auth.password }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
    {{- else }}
  password: {{ randAlphaNum 24 | b64enc | quote }}
    {{- end }}
  {{- else }}
    {{- if .Values.externalDatabase.password }}
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
    {{- else }}
  password: {{ randAlphaNum 24 | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end }}
