{{- if include "ephor.database.createSecret" . }}
{{- $secretName := include "ephor.database.secretName" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "ephor.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
    {{- if .Values.postgresql.auth.password }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
    {{- else if and $existingSecret $existingSecret.data.password }}
  password: {{ $existingSecret.data.password }}
    {{- else }}
  password: {{ randAlphaNum 24 | b64enc | quote }}
    {{- end }}
  {{- else }}
    {{- if .Values.externalDatabase.password }}
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
    {{- else if and $existingSecret $existingSecret.data.password }}
  password: {{ $existingSecret.data.password }}
    {{- else }}
  password: {{ randAlphaNum 24 | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end }}
