apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ephor.api.fullname" . }}
  labels:
    {{- include "ephor.api.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ include "ephor.database.url" . | quote }}
  SPRING_DATASOURCE_USERNAME: {{ include "ephor.database.username" . | quote }}
  LOGGING_STRUCTURED_FORMAT_CONSOLE: logstash
  AUTH_ENABLED: "true"
