apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ephor.api.fullname" . }}
  labels:
    {{- include "ephor.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "ephor.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/api/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "ephor.api.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "ephor.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- include "ephor.podSecurityContext" . | nindent 8 }}
      containers:
        - name: api
          image: {{ include "ephor.api.image" . }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          securityContext:
            {{- include "ephor.containerSecurityContext" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "ephor.api.fullname" . }}
            {{- with .Values.api.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ephor.database.secretName" . }}
                  key: password
            {{- with .Values.api.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          startupProbe:
            httpGet:
              path: {{ .Values.api.probes.startup.path }}
              port: http
            initialDelaySeconds: {{ .Values.api.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.api.probes.startup.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.api.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.api.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.api.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.api.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.api.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
