apiVersion: v1
kind: Service
metadata:
  name: {{ include "ephor.api.fullname" . }}
  labels:
    {{- include "ephor.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ephor.api.selectorLabels" . | nindent 4 }}
